- name: Add 1Password RPM key
  become: true
  ansible.builtin.rpm_key:
    fingerprint: "3FEF9748469ADBE15DA7CA80AC2D62742012EA22"
    key: "https://downloads.1password.com/linux/keys/1password.asc"
- name: Add 1Password repository
  become: true
  ansible.builtin.yum_repository:
    baseurl: "https://downloads.1password.com/linux/rpm/stable/$basearch"
    description: "1Password Stable Channel"
    enabled: true
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    includepkgs:
    - 1password
    - 1password-cli
    name: 1password
    repo_gpgcheck: true
- name: Install 1Password CLI
  become: true
  ansible.builtin.package:
    name: 1password-cli
    state: present
- name: Install 1Password UI
  become: true
  when: ansible_architecture == "x86_64"
  ansible.builtin.package:
    name: 1password
    state: present
