- name: Download dotfiles
  ansible.builtin.git:
    repo: git@github.com:puiterwijk/dotfiles.git
    dest: "{{ ansible_facts.user_dir }}/dotfiles"
- name: Setup dotfiles
  ansible.builtin.shell: "{{ ansible_facts.user_dir }}/dotfiles/setup.sh"
  args:
    chdir: "{{ ansible_facts.user_dir }}/dotfiles"
    creates: "{{ ansible_facts.user_dir }}/.ssh/config"
