- name: Make sure dnf and yum are not used
  become: true
  ansible.builtin.file:
    path: "/usr/bin/{{ item }}"
    mode: "0000"
  with_items:
  - yum
  - dnf
- name: Install some basic dependencies
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
  - git
  - tar
  - vim
  - wget
  - direnv
  - thefuck
- include_tasks: 1password.yml
- include_tasks: dotfiles.yml
