- name: Make sure dnf and yum are not used
  become: true
  ansible.builtin.copy:
    content: "#/usr/bin/bash\necho \"Use Ansible\"\nexit 1"
    dest: "/usr/bin/{{ item }}"
    mode: "755"
  with_items:
  - yum
  - dnf
- name: Add 1Password RPM key
  become: true
  ansible.builtin.rpm_key:
    fingerprint: "3FEF9748469ADBE15DA7CA80AC2D62742012EA22"
    key: "https://downloads.1password.com/linux/keys/1password.asc"
- name: Add 1Password repository
  become: true
  ansible.builtin.yum_repository:
    baseurl: "https://downloads.1password.com/linux/rpm/stable/$basearch"
    description: "1Password Stable Channel"
    enabled: true
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    includepkgs:
    - 1password-cli
    name: 1password
    repo_gpgcheck: true
- name: Install some basic dependencies
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
  - git
  - tar
  - vim
  - wget
  - direnv
  - thefuck
  - 1password-cli
- name: Download dotfiles
  ansible.builtin.git:
    repo: git@github.com:puiterwijk/dotfiles.git
    dest: "{{ ansible_facts.user_dir }}/dotfiles"
- name: Setup dotfiles
  ansible.builtin.shell: "{{ ansible_facts.user_dir }}/dotfiles/setup.sh"
  args:
    chdir: "{{ ansible_facts.user_dir }}/dotfiles"
    creates: "{{ ansible_facts.user_dir }}/.ssh/config"
