- name: Install some basic dependencies
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
  - git
  - tar
  - vim
- name: Download dotfiles
  ansible.builtin.git:
    repo: https://github.com/puiterwijk/dotfiles.git
    dest: "{{ ansible_facts.user_dir }}/dotfiles"
- name: Setup dotfiles
  ansible.builtin.shell: "{{ ansible_facts.user_dir }}/dotfiles/setup.sh"
  args:
    chdir: "{{ ansible_facts.user_dir }}/dotfiles"
    creates: "{{ ansible_facts.user_dir }}/.ssh/config"
